---
title: "Global Biodiversity & Population App"
author: "Rachel Kenny"
date: "2/10/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

###Load Libraries
```{r, load, message=FALSE}

library(tidyverse)
library(dplyr)
library(RColorBrewer)
library(ggplot2)
library(ggrepel)
library(readr)

bio <- read_csv("IUCN_thr_species_data.csv")
View(bio)

bio <- gather(bio, species_type, thr_count, Mammals:Fishes, factor_key=TRUE)

View(bio)

```

###Example bar graph for Page 1 of App
```{r, ggplot}

#Now we just need to figure out how to replace all this with inputs!

bio_df <- dplyr::filter(bio, Country == "Algeria" | Country == "Egypt")  
  

country_bio_graph <- ggplot(bio_df, aes(x=species_type, y=thr_count, fill=Country))+
  geom_bar(stat='identity', position='dodge')+
  ggtitle("Comparison of Threatened Species Count for Algeria and Egypt")+
  theme_classic()+
  xlab("Species Type")+
  ylab("Count of Threatened Species")+
  theme(axis.title = element_text(face="bold"), title = element_text(face="bold"))

country_bio_graph

```

